version: '3.7'
services:
    my-app:
      container_name: v1
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - 3001:3000
      environment:
        - CHOKIDAR_USEPOLLING=true