//Type test
export const GET_TEST_FROM_API="GET_TEST_FROM_API";
export const GET_TEST="GET_TEST";
export const ADD_TEST="ADD_TEST";
export const UPDATE_TEST="UPDATE_TEST";
export const UPDATE_ALL_TEST="UPDATE_ALL_TEST";
export const DELETE_TEST="DELETE_TEST";

//Modal
export const UPDATE_MODAL="UPDATE_MODAL";
export const GET_MODAL="GET_MODAL";

//Param
export const UPDATE_PARAM="UPDATE_PARAM";
export const GET_PARAM="GET_MODAL";

//MerchantList
export const UPDATE_MERCHANT_LIST="UPDATE_MERCHANT_LIST";
export const GET_MERCHANT_LIST="GET_MERCHANT_LIST";
export const ADD_MERCHANT_LIST="ADD_MERCHANT_LIST";
export const ADD_MERCHANT_LISTS="ADD_MERCHANT_LISTS";

//MerchantList from database
export const UPDATE_MERCHANT_LIST_FROM_DATABASE="UPDATE_MERCHANT_LIST_FROM_DATABASE";
export const GET_MERCHANT_LIST_FROM_DATABASE="GET_MERCHANT_LIST_FROM_DATABASE";
export const ADD_MERCHANT_LIST_FROM_DATABASE="ADD_MERCHANT_LIST_FROM_DATABASE";
export const ADD_MERCHANT_LISTS_FROM_DATABASE="ADD_MERCHANT_LISTS_FROM_DATABASE";

